copytiles.exe:
	g++ -std=c++11 -I /usr/include/gdal -I ../libtilingtools/ -I ../../cpp_common_utils/ -L ../libtilingtools/ copytiles.cpp consoleutils.cpp stringfuncs.h filesystemfuncs.h -o copytiles.exe -l gdal -l tilingtools -l sqlite3 -l gd -l pthread	
	
	
	
	
