copytiles.exe:
	g++ -O3 -std=c++11 -I /usr/include/gdal -I ../libtilingtools/ -I ../../cpp_common_utils/ -L ../libtilingtools/ copytiles.cpp -o copytiles.exe -l gdal -l tilingtools -l sqlite3 -l pthread	
	
	
	
	
