gcc -std=c++11 -I /usr/include/gdal -c consoleutils.cpp -o consoleutils.o
gcc -std=c++11 -I /usr/include/gdal -c filesystemfuncs.cpp -o filesystem.o
gcc -std=c++11 -I /usr/include/gdal -c hystogram.cpp -o hystogram.o


